export * from "./auth.schema"
export * from "./student.schema"
export * from "./checkin.schema"
export * from "./sync.schema"
export * from "./student-group.schema"
export * from "./points.schema"
export * from "./minigame.schema"
export * from "./friends.schema"