// Reads the offline department+gender-balanced boing (district) split -
// computed in ../../freshmen-random-house per the "further randoming happens
// there, not in this app" rule - and generates a .sql file of upserts into
// student_group. Doesn't touch the DB directly, same reasoning as
// import-group-results.ts: D1 only reachable via Workers binding or
// `wrangler d1 execute`.
//
// Expects a CSV with columns: student_id (the human student number, e.g.
// 6912345623 - NOT the app's internal uuid), group_number, subgroup_number.
// Adjust EXPECTED_COLUMNS below if freshmen-random-house's actual output
// uses different header names.
//
// Usage:
//   bun run import-student-boing.ts <path-to-boing-result.csv>
//   cd ../../packages/db && wrangler d1 execute DB --local --file=./import-student-boing.sql --config ../../apps/web/wrangler.jsonc
//   (repeat with --remote once the local run looks right)

import parse from "csv-simple-parser";

type BoingRow = {
  student_id: string;
  group_number: string;
  subgroup_number: string;
};

const csvPath = process.argv[2];
if (!csvPath) {
  console.error("Usage: bun run import-student-boing.ts <path-to-boing-result.csv>");
  process.exit(1);
}

const outPath = "../../packages/db/import-student-boing.sql";

const file = Bun.file(csvPath);
if (!(await file.exists())) {
  console.error(`Not found: ${csvPath}`);
  process.exit(1);
}

const rows = parse((await file.text()).trim(), { header: true, delimiter: "," }).filter(Boolean) as BoingRow[];

const lines: string[] = [
  "-- Generated by scripts/stats/import-student-boing.ts - do not hand-edit.",
  "-- Upserts the offline department+gender-balanced boing split into student_group, resolved by students.student_id.",
];

let skipped = 0;
for (const row of rows) {
  const studentId = row.student_id;
  const groupNumber = Number(row.group_number);
  const subgroupNumber = Number(row.subgroup_number);
  if (!studentId || !Number.isFinite(groupNumber) || !Number.isFinite(subgroupNumber)) {
    skipped++;
    continue;
  }
  const escapedStudentId = studentId.replace(/'/g, "''");
  lines.push(
    `INSERT INTO student_group (id, student_id, group_number, subgroup_number, created_at, updated_at)
SELECT lower(hex(randomblob(16))), s.id, ${groupNumber}, ${subgroupNumber}, unixepoch(), unixepoch()
FROM students s WHERE s.student_id = '${escapedStudentId}'
ON CONFLICT(student_id) DO UPDATE SET group_number = excluded.group_number, subgroup_number = excluded.subgroup_number, updated_at = excluded.updated_at;`,
  );
}

await Bun.write(outPath, lines.join("\n") + "\n");

console.log(`Wrote ${rows.length - skipped} upserts to ${outPath} (skipped ${skipped} incomplete rows).`);
